version: 0.1

workflows:
  main:
    jobs:
    - build

jobs:
  build:
    steps:
    - clone
    - run: wodby ci init $WODBY_BUILD_ID
    - run: wodby ci build --build-arg DISCOURSE_GIT_VERSION="$(git rev-parse HEAD)"
    - run: wodby ci push
    - run: wodby ci deploy
